# Generated by Django 5.2.10 on 2026-03-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientProfile",
        ),
    ]
