# Generated by Django 5.2.10 on 2026-03-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_remove_appointmentreminder_appointment_and_more"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctorreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="doctorreview",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="appointments.appointment",
            ),
        ),
    ]
