# Generated by Django 5.2.10 on 2026-03-04 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="message",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="MedicalKnowledgeBase",
        ),
        migrations.DeleteModel(
            name="ChatbotFeedback",
        ),
    ]
