# Generated by Django 5.2.10 on 2026-03-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentreminder",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="rescheduled_from",
        ),
        migrations.DeleteModel(
            name="AppointmentDocument",
        ),
        migrations.DeleteModel(
            name="AppointmentReminder",
        ),
    ]
